# GitHub Actions My

name: My-FirstActions
env:
  APPLICATION_NAME: "FirstWay"
  PACKAGE_NAME    : "My-deploy-ver-${{ github.sha }}"

on: 
  workflow_dispatch:  
#  push:
#    branches:
#      - main

jobs:
  my_testing:
   runs-on: ubuntu-latest
   
   steps:
     - name: Print Hello in Test
       run: echo "Hello World from Testing"

     - name: Execute few commands
       run: |
         echo "Application name: ${{ env.APPLICATION_NAME }}"
         echo "Package name: ${{ env.PACKAGE_NAME }}"

     - name: Git clone my Repo
       uses: actions/checkout@v1

     - name: List current folder
       run: |
         pwd
         echo "-------"
         ls -la


  my_deploy:
   runs-on: ubuntu-latest
   needs: my_testing
   env:
     VAR1: "var1"
   
   steps:
     - name: Print Hello in Deploy
       run: echo "Hello World from Deploy"
       
     - name: Check Git
       run: |
         git --version
         zip --version


     - name: Print Var1
       run: |
         echo "Var1: ${{ env.VAR1 }}"
         echo "Var2: $LOCAL_VAR2"
       env:
         LOCAL_VAR2: "loc_var2" 
